AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'public/uploads/**/**/**/*'
    - 'config/spring.rb'
    - 'config/ansible/**/*'
    - 'config/puma/**/*'
    - '.pryrc'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  SuggestExtensions: false
  NewCops: disable

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 140

Metrics/AbcSize:
  Max: 60

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 170

Metrics/PerceivedComplexity:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
